version: '3.7'

services:

  app:
    container_name: app
    build: .
    # volumes:
    #   - ./app/:/app
    #command: tail -F anything # keep it running
    working_dir: /app
    env_file:
      - .env
    #entrypoint: ['sh', '/app/init.sh']
    depends_on:
        - mongo
  
  downloader:
    container_name: downloader
    build: . 
    # volumes:
    #   - ./app/:/app
    working_dir: /app
    entrypoint: ['python', 'refresh.py']
    env_file:
      - .env
    depends_on:
        - app
        
  mongo:
    image: mongo:4
    container_name: mongodb
    restart: always
    volumes:
      - mongodata:/data/db
    expose:
      - 27017


volumes:
  mongodata: